### ISSUE TITLE
Send ISO 3166-1 Alpha2 country code instead of name in dynamic shipping callback

### ISSUE THREAD

**Issue by madsoliver** [vippsas/vipps-checkout-api#44]
Country names are translatable, iso-codes are not.
Therefore it makes sense to send iso-code in a server-server request.

**Like this:**

```
{
    "streetAddress": "Skolevegen 1",
    "postalCode": "7604",
    "region": "Levanger",
    "country": "NO"
}
```

In order to not break integrations allready set up, you can instead do:

```
{
    "streetAddress": "Skolevegen 1",
    "postalCode": "7604",
    "region": "Levanger",
    "country": "Nårvei",
    "country_iso": "NO"
}
```

**Comment by Ceredron** [comment]
Good idea! We will consider this for V3 of our API.
