### ISSUE TITLE
JS SDK Event 'shipping_option_selected' should also pass ShippingOption id

### ISSUE THREAD

**Issue by madsoliver** [vippsas/vipps-checkout-api#71]
In order to select shipping-option, and live-update webshop cart, we need the Shipping Option id provided (by us) in the dynamic shipping options webhook.

**Today we get something like:**
```
brand: "Bring"
description: "Leveringstid avhenger av postnummer"
price:  {fractionalDenomination: 20700, currency: 'NOK'}
product: "Pakke til hentested"
```

**But in order to properly select the correct Shipping Option in the webshop we should get something like:**

```
id: "our_unique_shipping_option_id_12345"
brand: "Bring"
description: "Leveringstid avhenger av postnummer"
price:  {fractionalDenomination: 20700, currency: 'NOK'}
product: "Pakke til hentested"
```

**Comment by eirikv** [comment]
Hey! Thanks for the feedback.
We've just rolled out a new version of the SDK where the `id` is forwarded for shipping options.

You can find the documentation of the [changes here](https://github.com/vippsas/vipps-checkout-api/blob/main/vipps-checkout-api.md#sdk-events ).
