### ISSUE TITLE
Add email_verified flag to checkout poll userDetails

### ISSUE THREAD

**Issue by madsoliver** [vippsas/vipps-checkout-api#80]
We want to login our customers after successful checkout.
In the following poll we receive `userDetails[email]` .
It would be useful to also receive `userDetails[email_verified]: true|false` .

Then we can login users that have verified email adresses.

Side note: maybe adding a "Please confirm your email to automatically be logged in" in the checkout GUI also is a good idea?

**Comment by Ceredron** [comment]
Checkout is not in itself a login solution. Such use cases should employ the Vipps Login API directly. 
The reason for this is that the user has only consented to sharing their personal data to perform the payment, not for signing up for an account.
