### ISSUE TITLE
Making Shippingaddress > Country a dropdown menu instead of freetext-field

### ISSUE THREAD

**Issue by madsoliver** [vippsas/vipps-checkout-api#81]
Hi,
Today you can write whatever you want for country when filling out a specific shipping address in the chekout gui.
This might be useful for the most pretentious among us, but for the rest of us, choosing your country in a dropdown is easier.
Then you can send us a country-iso-code in the dynamic shipping options webhook as well as when we poll for shipping address.

**Comment by Ceredron** [comment]
Thanks for the suggestion. This is now in production.
